// <auto-generated />
using System;
using BonGoo.Web.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BonGoo.Web.API.Migrations
{
    [DbContext(typeof(BonGooDbContext))]
    [Migration("20260310170820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BonGoo.Web.API.Entities.Abgabestelle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Drucker")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Einzeldruck")
                        .HasColumnType("boolean");

                    b.Property<bool>("Kassastelle")
                        .HasColumnType("boolean");

                    b.Property<bool>("TakeAway")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VeranstaltungId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("Abgabestellen", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Bedienung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VeranstaltungId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("Bedienungen", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.BedienungBarmittel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Abfuhr")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BedienungId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Betrag")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Wechselgeld")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BedienungId");

                    b.ToTable("BedienungenBarmittel");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Bestellung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BedienungId")
                        .HasColumnType("uuid");

                    b.Property<int>("BestellNr")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SammelrechnungId")
                        .HasColumnType("uuid");

                    b.Property<string>("TischNr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VeranstaltungId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BedienungId");

                    b.HasIndex("SammelrechnungId");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("Bestellungen", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Bon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Abgerechnet")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AbgerechnetStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Anmerkung")
                        .HasColumnType("text");

                    b.Property<Guid>("BestellungId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Druck")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DruckStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eigenverbrauch")
                        .HasColumnType("boolean");

                    b.Property<bool>("Einpacken")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ErzeugtStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Fremdverpflegung")
                        .HasColumnType("boolean");

                    b.Property<bool>("Kassiert")
                        .HasColumnType("boolean");

                    b.Property<int>("Menge")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProduktId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Selbstabholung")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Zurückgestellt")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BestellungId");

                    b.HasIndex("ProduktId");

                    b.ToTable("Bons", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.CounterProdukt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbgabestelleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Menge")
                        .HasColumnType("integer");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AbgabestelleId");

                    b.ToTable("CounterProdukte", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.EinAuszahlung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Auszahlung")
                        .HasColumnType("boolean");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<decimal>("Betrag")
                        .HasColumnType("numeric");

                    b.Property<string>("Betroffener")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Einzahlung")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VeranstaltungId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("EinAuszahlungen");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Festführer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prozente")
                        .HasColumnType("integer");

                    b.Property<string>("RechnungName")
                        .HasColumnType("text");

                    b.Property<string>("RechnungPLZOrt")
                        .HasColumnType("text");

                    b.Property<string>("RechnungStrasseHnr")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VeranstaltungId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("Festführer");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Fremdverpflegung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Anzahl")
                        .HasColumnType("integer");

                    b.Property<bool>("Ausgedruckt")
                        .HasColumnType("boolean");

                    b.Property<string>("BonText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Empfänger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VeranstaltungId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("Fremdverpflegungen");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.KassaCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("KassaId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VeranstaltungId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KassaCodes", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Produkt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbgabestelleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ausverkauft")
                        .HasColumnType("boolean");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CounterProduktId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HatCounter")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Preis")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AbgabestelleId");

                    b.HasIndex("CounterProduktId");

                    b.ToTable("Produkte", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.QrLoginToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AbgabestelleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BedienungId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsedByClientInfo")
                        .HasColumnType("text");

                    b.Property<string>("UsedByIpAddress")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AbgabestelleId");

                    b.HasIndex("BedienungId");

                    b.ToTable("QrLoginTokens", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Sammelrechnung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FestführerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HatFestführer")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VeranstaltungId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FestführerId");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("Sammelrechnungen");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PasswordResetTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VeranstalterId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("VerificationTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("VeranstalterId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Veranstalter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("bytea");

                    b.Property<string>("Ort")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Plz")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Strasse")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Veranstalter", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Veranstaltung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("Bis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VeranstalterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Von")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("VeranstalterId");

                    b.ToTable("Veranstaltungen", (string)null);
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Abgabestelle", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Veranstaltung", "Veranstaltung")
                        .WithMany("Abgabestellen")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Bedienung", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Veranstaltung", "Veranstaltung")
                        .WithMany("Bedienungen")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.BedienungBarmittel", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Bedienung", "Bedienung")
                        .WithMany("Barmittel")
                        .HasForeignKey("BedienungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bedienung");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Bestellung", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Bedienung", "Bedienung")
                        .WithMany("Bestellungen")
                        .HasForeignKey("BedienungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BonGoo.Web.API.Entities.Sammelrechnung", "Sammelrechnung")
                        .WithMany("Bestellungen")
                        .HasForeignKey("SammelrechnungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BonGoo.Web.API.Entities.Veranstaltung", "Veranstaltung")
                        .WithMany("Bestellungen")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bedienung");

                    b.Navigation("Sammelrechnung");

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Bon", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Bestellung", "Bestellung")
                        .WithMany("Bons")
                        .HasForeignKey("BestellungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BonGoo.Web.API.Entities.Produkt", "Produkt")
                        .WithMany("Bons")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bestellung");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.CounterProdukt", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Abgabestelle", "Abgabestelle")
                        .WithMany("CounterProdukte")
                        .HasForeignKey("AbgabestelleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abgabestelle");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.EinAuszahlung", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Veranstaltung", "Veranstaltung")
                        .WithMany("EinAuszahlungen")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Festführer", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Veranstaltung", "Veranstaltung")
                        .WithMany("Festführer")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Fremdverpflegung", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Veranstaltung", "Veranstaltung")
                        .WithMany("Fremdverpflegungen")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Produkt", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Abgabestelle", "Abgabestelle")
                        .WithMany("Produkte")
                        .HasForeignKey("AbgabestelleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BonGoo.Web.API.Entities.CounterProdukt", "CounterProdukt")
                        .WithMany("Produkte")
                        .HasForeignKey("CounterProduktId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Abgabestelle");

                    b.Navigation("CounterProdukt");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.QrLoginToken", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Abgabestelle", "Abgabestelle")
                        .WithMany("QrLoginTokens")
                        .HasForeignKey("AbgabestelleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BonGoo.Web.API.Entities.Bedienung", "Bedienung")
                        .WithMany("QrLoginTokens")
                        .HasForeignKey("BedienungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Abgabestelle");

                    b.Navigation("Bedienung");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.RefreshToken", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Sammelrechnung", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Festführer", "Festführer")
                        .WithMany("Sammelrechnungen")
                        .HasForeignKey("FestführerId");

                    b.HasOne("BonGoo.Web.API.Entities.Veranstaltung", "Veranstaltung")
                        .WithMany("Sammelrechnungen")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festführer");

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.User", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Veranstalter", "Veranstalter")
                        .WithMany()
                        .HasForeignKey("VeranstalterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Veranstalter");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Veranstalter", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Veranstaltung", b =>
                {
                    b.HasOne("BonGoo.Web.API.Entities.Veranstalter", "Veranstalter")
                        .WithMany("Veranstaltungen")
                        .HasForeignKey("VeranstalterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstalter");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Abgabestelle", b =>
                {
                    b.Navigation("CounterProdukte");

                    b.Navigation("Produkte");

                    b.Navigation("QrLoginTokens");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Bedienung", b =>
                {
                    b.Navigation("Barmittel");

                    b.Navigation("Bestellungen");

                    b.Navigation("QrLoginTokens");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Bestellung", b =>
                {
                    b.Navigation("Bons");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.CounterProdukt", b =>
                {
                    b.Navigation("Produkte");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Festführer", b =>
                {
                    b.Navigation("Sammelrechnungen");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Produkt", b =>
                {
                    b.Navigation("Bons");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Sammelrechnung", b =>
                {
                    b.Navigation("Bestellungen");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Veranstalter", b =>
                {
                    b.Navigation("Veranstaltungen");
                });

            modelBuilder.Entity("BonGoo.Web.API.Entities.Veranstaltung", b =>
                {
                    b.Navigation("Abgabestellen");

                    b.Navigation("Bedienungen");

                    b.Navigation("Bestellungen");

                    b.Navigation("EinAuszahlungen");

                    b.Navigation("Festführer");

                    b.Navigation("Fremdverpflegungen");

                    b.Navigation("Sammelrechnungen");
                });
#pragma warning restore 612, 618
        }
    }
}
